### PR TITLE
Typescript Declarations / Server Side rendering compatibility

### LINKED ISSUE #72: [Player] Next.js: Module not found: Can't resolve 'icecast-metadata-player'
Hi

First of all, thank you so much for this library!

It worked flawlessly on a plain HTML/JS page as a proof-of-concept.
But unfortunately, it seems to not work out using Next.js. I get the error:
```
Module not found: Can't resolve 'icecast-metadata-player'
```

You can reproduce the error here:
https://codesandbox.io/s/silly-gates-4wppo?file=/pages/index.js

This is probably because Node.js itself cannot import the player, as seen here:
https://codesandbox.io/s/admiring-hugle-64d86?file=/src/index.js

Is there a way to make this work? Maybe by exporting a dummy object, like the HLS player is doing (https://codesandbox.io/s/admiring-hugle-64d86?file=/src/index.js)

### PR DESCRIPTION
**Pull request by eshaz**
### Features
* Typescript declarations for IcecastMetadataPlayer
  * Thanks to @michaelschufi for the idea and initial version!

### Fixes
* Add compatibility for NodeJS based server side rendering frameworks (i.e. Next.js)
  * Add `main` entry point in package.json
  * Add `"type": "module"` and update import syntax for NodeJS ECMAScript modules compatibility
  * Resolves #72 
* Various typo and documentation fixes

### CODE REVIEW

File: src/icecast-metadata-player/types/icecast-metadata-player.d.ts [hunk 1]
```diff
@@ -0,0 +1,205 @@
+declare module "icecast-metadata-player" {
+  /** Icecast/Shoutcast ICY metadata values */
+  export interface IcyMetadata {
+    StreamTitle?: string; // ICY metadata updates are sometimes just an empty string, which will result in an empty object
```
Comment (CharlesSchimmel) [inline src/icecast-metadata-player/types/icecast-metadata-player.d.ts:4]: I think it will look a little more tidy if we put comments/documentation above the property and wrap comments/documentation to 80-120 characters (and use multi-line comment format if the line is wrapped.) JSDoc style, I guess.

**Review by CharlesSchimmel — APPROVED** [review]
